version: '2'

services:

  full-teaching-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=full_teaching
      - MYSQL_USER=ft-root
      - MYSQL_PASSWORD=pass

  full-teaching-openvidu-server-kms:
    image: openvidu/openvidu-server-kms:1.7.0
    ports:
      - 8443:8443
    environment:
      - KMS_STUN_IP=stun.l.google.com
      - KMS_STUN_PORT=19302
      - openvidu.secret=MY_SECRET
      - openvidu.publicurl=docker

  full-teaching:
    image: pablofuente/full-teaching
    links:
      - full-teaching-mysql
      - full-teaching-openvidu-server-kms
    ports:
      - 5000:5000
    environment:
      - WAIT_HOSTS=full-teaching-mysql:3306
      - WAIT_HOSTS_TIMEOUT=120
      - MYSQL_PORT_3306_TCP_ADDR=full-teaching-mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_ENV_MYSQL_DATABASE=full_teaching
      - MYSQL_ENV_MYSQL_USER=ft-root
      - MYSQL_ENV_MYSQL_PASSWORD=pass
      - server.port=5000
      - openvidu.url=https://full-teaching-openvidu-server-kms:8443
      - openvidu.secret=MY_SECRET
